baseURL: https://turuibo.github.io/blog_site/
languageCode: en-us
theme: hugo-PaperMod
params:
  homeInfoParams:
    Title: Welcome to Ruibo blog site
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"
