baseURL: https://turuibo.github.io/
title: Ruibo-blog
languageCode: en-us
theme: hugo-PaperMod

enableEmoji: true


languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags/
          weight: 10

        
params:
  homeInfoParams:
    Title: Ruibo blog site
    Content: Blogs of Machine Learning

  socialIcons: # optional
    - name: "google scholar"
      url: "https://scholar.google.se/citations?user=auIx_r0AAAAJ&hl=en"
    - name: "github"
      url: "https://github.com/TURuibo"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ruibo-t-6017a3139/"

  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
