baseURL: https://turuibo.github.io/blog_site/
languageCode: en-us
theme: hugo-PaperMod
params:
  homeInfoParams:
    Title: Ruibo blog site
    Content: Blogs of Machine Learning

  socialIcons: # optional
    - name: "google scholar"
      url: "https://scholar.google.se/citations?user=auIx_r0AAAAJ&hl=en"
    - name: "github"
      url: "https://github.com/TURuibo"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ruibo-t-6017a3139/"